name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log in to Docker Hub
        env:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
        run: |
          docker login -u $username -p $password
      - name: Build the Docker image
        run: |
          docker build . -f dockerfile -t ${{secrets.DOCKERHUB_USERNAME}}/demo-devops:latest
      - name: Push the Docker image
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/demo-devops:latest
